apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
          - name: demoapp
            image: anil181/demoapp:latest
            env:
              - name: TIME_SERVICE_URL
                valueFrom:
                 configMapKeyRef:
                    name: demoapp-configmap
                    key: time-service
            volumeMounts:
            - name: demo-configmap-volume
              mountPath: /etc/config
      volumes:
         - name: demo-configmap-volume
           configMap:
             name: demoapp-configmap